image:
  repository: krumware/baseline-golang-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.

  tag: "20230823T175417"
imagePullSecrets:
  - name: nexus-push-user
service:
  type: ClusterIP
  port: 1323
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: golang.212.2.241.168.sslip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - golang.212.2.241.168.sslip.io
      secretName: baseline-golang-app-tls
resources:
  limits:
    cpu: 50m
    memory: 300Mi
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetMemoryUtilizationPercentage: 1
